server.port: 7002

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db
  auto-index-creation: true

logging:
  level:
    root: INFO
    com.luo: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080
